SPLIT_KEYBOARD = yes
SPLIT_HAND_PIN = C14

ENCODER_ENABLE = no

AUDIO_ENABLE = yes
AUDIO_DRIVER = pwm_hardware

SERIAL_DRIVER = usart

BACKLIGHT_ENABLE = no
RGBLIGHT_ENABLE = no
WS2812_DRIVER = pwm

EEPROM_DRIVER = spi

MCU = STM32F411
BOOTLOADER = stm32-dfu

AUTOCORRECT_ENABLE = no

CUSTOM_BOOTMAGIC_ENABLE = no
CUSTOM_UNICODE_ENABLE = no
HAPTIC_ENABLE = no

OLED_ENABLE = no
OLED_DRIVER = custom

SWAP_HANDS_ENABLE = no
TAP_DANCE_ENABLE = no

WPM_ENABLE = no
